development:
  adapter: postgresql
  encoding: unicode
  database: shop_app_development
  pool: 5
  username: adrian
  password: akuku

test:
  adapter: postgresql
  encoding: unicode
  database: shop_app_test
  pool: 5
  username: adrian
  password: akuku

production:
  adapter: postgresql
  encoding: unicode
  database: shop_app_production
  pool: 5
  username: adrian
  password: akuku
